[package]
name = "isscore"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
sgp4 = "2.3"
practical-astronomy-rust = "0.2.4"
log = "0.4"
env_logger = "0.11"
android_logger = "0.13"
